ALTER TABLE cotizacion ADD CANTIDAD_OFRECIDA INT NULL DEFAULT NULL;
DROP TRIGGER IF EXISTS TR_CALCULAR_TOTAL_COTIZACION;
DELIMITER //
CREATE TRIGGER TR_CALCULAR_TOTAL_COTIZACION
BEFORE INSERT ON cotizacion
FOR EACH ROW
BEGIN
    DECLARE v_cantidad INT;
    DECLARE v_porcentaje_iva DECIMAL(5,2);
    DECLARE v_neto_total INT;

    IF NEW.CANTIDAD_OFRECIDA IS NOT NULL THEN
        SET v_cantidad = NEW.CANTIDAD_OFRECIDA;
    ELSE
        SELECT CANTIDAD_REGULAR INTO v_cantidad 
        FROM MATRIZ_ITEM 
        WHERE ID_MATRIZ_ITEM = NEW.ID_MATRIZ_ITEM;
    END IF;

    SELECT PORCENTAJE INTO v_porcentaje_iva 
    FROM IVA 
    WHERE ID_IVA = NEW.ID_IVA;

    SET v_neto_total = v_cantidad * NEW.VALOR_UNITARIO;

    SET NEW.VALOR_TOTAL = ROUND(v_neto_total * (1 + (v_porcentaje_iva / 100)), 0);
END;
//
DELIMITER ;
